# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'MoneyBack' do
    pod 'Google/SignIn'
end

target 'MoneyBackTests' do

end

target 'MoneyBackUITests' do

end

